[[language]]
name = "rust"
auto-format = true
language-servers = [ "rust-analyzer" ]
indent = { tab-width = 4, unit = "    " }

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
# Utilise "clippy" pour le diagnostic.
check.command = "clippy"

# Active toutes les "features" du Cargo.toml.
cargo.allFeatures = true

# Indispensable pour l'autocomplétion des macros.
procMacro.enable = true

# Configuration des "inlay hints" (indications dans le code).
inlayHints.bindingModeHints.enable = true
inlayHints.chainingHints.enable = true
inlayHints.closingBraceHints.enable = true
inlayHints.closingBraceHints.minLines = 10
inlayHints.parameterHints.enable = true
inlayHints.typeHints.enable = true
inlayHints.typeHints.hideLessSpecificTypes = true


[[language]]
name = "json"
scope = "source.json"
file-types = ["json", "jsonc", "geojson"]
# Association avec la grammaire tree-sitter
grammar = "json" 
# Commentaire pour le code, si nécessaire
comment-token = "//"
# Configuration de l'indentation
indent = { tab-width = 2, unit = "  " }
